name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v3
      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: Xotabu4/selenoid-github-action@v2
      # добавляем gradle wrapper
      - run: gradle wrapper
      # запускаем тесты
      - run: ./gradlew clean test -Dtest.single=* -Dselenide.remote=http://localhost:4444/wd/hub
      # скачиваем историю прогонов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
#          - uses: Send Telegram notification
#            run: |
#              curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
#              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
#              -d text="Тесты успешно пройдены! Статистика и отчет доступны по ссылке: https://example.com/allure-report"

      # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history